title: Jeet Arvindkumar Swami
logo: /Images/JEET SWAMI.png
description: I am a Data Analyst with two years of experience in data modeling, analysis, and reporting. I specialize in handling large datasets and transforming raw data into actionable insights using Python, SQL, and Tableau. My expertise includes BI tools, ETL processes, workflow automation, and maintaining data integrity. I have experience gathering requirements, collaborating with stakeholders, and creating reports to support data-driven decision-making. Proficient in Microsoft applications, I excel in problem-solving, communication, and teamwork, thriving in fast-paced environments.
show_downloads: false
theme: jekyll-theme-minimal
